export const countries = [
    {flag: "ad.png", name: "Andorra"},
    {flag: "ae.png", name: "United Arab Emirates"},
    {flag: "af.png", name: "Afghanistan"},
    {flag: "ag.png", name: "Antigua and Barbuda"},
    {flag: "ai.png", name: "Anguilla"},
    {flag: "al.png", name: "Albania"},
    {flag: "am.png", name: "Armenia"},
    {flag: "ao.png", name: "Angola"},
    {flag: "aq.png", name: "Antarctica"},
    {flag: "ar.png", name: "Argentina"},
    {flag: "as.png", name: "American Samoa"},
    {flag: "at.png", name: "Austria"},
    {flag: "au.png", name: "Australia"},
    {flag: "aw.png", name: "Aruba"},
    {flag: "ax.png", name: "Åland Islands"},
    {flag: "az.png", name: "Azerbaijan"},
    {flag: "ba.png", name: "Bosnia and Herzegovina"},
    {flag: "bb.png", name: "Barbados"},
    {flag: "bd.png", name: "Bangladesh"},
    {flag: "be.png", name: "Belgium"},
    {flag: "bf.png", name: "Burkina Faso"},
    {flag: "bg.png", name: "Bulgaria"},
    {flag: "bh.png", name: "Bahrain"},
    {flag: "bi.png", name: "Burundi"},
    {flag: "bj.png", name: "Benin"},
    {flag: "bl.png", name: "Saint Barthélemy"},
    {flag: "bm.png", name: "Bermuda"},
    {flag: "bn.png", name: "Brunei"},
    {flag: "bo.png", name: "Bolivia"},
    {flag: "bq.png", name: "Caribbean Netherlands"},
    {flag: "br.png", name: "Brazil"},
    {flag: "bs.png", name: "Bahamas"},
    {flag: "bt.png", name: "Bhutan"},
    {flag: "bv.png", name: "Bouvet Island"},
    {flag: "bw.png", name: "Botswana"},
    {flag: "by.png", name: "Belarus"},
    {flag: "bz.png", name: "Belize"},
    {flag: "ca.png", name: "Canada"},
    {flag: "cc.png", name: "Cocos (Keeling) Islands"},
    {flag: "cd.png", name: "DR Congo"},
    {flag: "cf.png", name: "Central African Republic"},
    {flag: "cg.png", name: "Republic of the Congo"},
    {flag: "ch.png", name: "Switzerland"},
    {flag: "ci.png", name: "Côte d'Ivoire (Ivory Coast)"},
    {flag: "ck.png", name: "Cook Islands"},
    {flag: "cl.png", name: "Chile"},
    {flag: "cm.png", name: "Cameroon"},
    {flag: "cn.png", name: "China"},
    {flag: "co.png", name: "Colombia"},
    {flag: "cr.png", name: "Costa Rica"},
    {flag: "cu.png", name: "Cuba"},
    {flag: "cv.png", name: "Cape Verde"},
    {flag: "cw.png", name: "Curaçao"},
    {flag: "cx.png", name: "Christmas Island"},
    {flag: "cy.png", name: "Cyprus"},
    {flag: "cz.png", name: "Czechia"},
    {flag: "de.png", name: "Germany"},
    {flag: "dj.png", name: "Djibouti"},
    {flag: "dk.png", name: "Denmark"},
    {flag: "dm.png", name: "Dominica"},
    {flag: "do.png", name: "Dominican Republic"},
    {flag: "dz.png", name: "Algeria"},
    {flag: "ec.png", name: "Ecuador"},
    {flag: "ee.png", name: "Estonia"},
    {flag: "eg.png", name: "Egypt"},
    {flag: "eh.png", name: "Western Sahara"},
    {flag: "er.png", name: "Eritrea"},
    {flag: "es.png", name: "Spain"},
    {flag: "et.png", name: "Ethiopia"},
    {flag: "fi.png", name: "Finland"},
    {flag: "fj.png", name: "Fiji"},
    {flag: "fk.png", name: "Falkland Islands"},
    {flag: "fm.png", name: "Micronesia"},
    {flag: "fo.png", name: "Faroe Islands"},
    {flag: "fr.png", name: "France"},
    {flag: "ga.png", name: "Gabon"},
    {flag: "gb.png", name: "United Kingdom"},
    {flag: "gb-eng.png", name: "England"},
    {flag: "gb-nir.png", name: "Northern Ireland"},
    {flag: "gb-sct.png", name: "Scotland"},
    {flag: "gb-wls.png", name: "Wales"},
    {flag: "gd.png", name: "Grenada"},
    {flag: "ge.png", name: "Georgia"},
    {flag: "gf.png", name: "French Guiana"},
    {flag: "gg.png", name: "Guernsey"},
    {flag: "gh.png", name: "Ghana"},
    {flag: "gi.png", name: "Gibraltar"},
    {flag: "gl.png", name: "Greenland"},
    {flag: "gm.png", name: "Gambia"},
    {flag: "gn.png", name: "Guinea"},
    {flag: "gp.png", name: "Guadeloupe"},
    {flag: "gq.png", name: "Equatorial Guinea"},
    {flag: "gr.png", name: "Greece"},
    {flag: "gs.png", name: "South Georgia"},
    {flag: "gt.png", name: "Guatemala"},
    {flag: "gu.png", name: "Guam"},
    {flag: "gw.png", name: "Guinea-Bissau"},
    {flag: "gy.png", name: "Guyana"},
    {flag: "hk.png", name: "Hong Kong"},
    {flag: "hm.png", name: "Heard Island and McDonald Islands"},
    {flag: "hn.png", name: "Honduras"},
    {flag: "hr.png", name: "Croatia"},
    {flag: "ht.png", name: "Haiti"},
    {flag: "hu.png", name: "Hungary"},
    {flag: "id.png", name: "Indonesia"},
    {flag: "ie.png", name: "Ireland"},
    {flag: "il.png", name: "Israel"},
    {flag: "im.png", name: "Isle of Man"},
    {flag: "in.png", name: "India"},
    {flag: "io.png", name: "British Indian Ocean Territory"},
    {flag: "iq.png", name: "Iraq"},
    {flag: "ir.png", name: "Iran"},
    {flag: "is.png", name: "Iceland"},
    {flag: "it.png", name: "Italy"},
    {flag: "je.png", name: "Jersey"},
    {flag: "jm.png", name: "Jamaica"},
    {flag: "jo.png", name: "Jordan"},
    {flag: "jp.png", name: "Japan"},
    {flag: "ke.png", name: "Kenya"},
    {flag: "kg.png", name: "Kyrgyzstan"},
    {flag: "kh.png", name: "Cambodia"},
    {flag: "ki.png", name: "Kiribati"},
    {flag: "km.png", name: "Comoros"},
    {flag: "kn.png", name: "Saint Kitts and Nevis"},
    {flag: "kp.png", name: "North Korea"},
    {flag: "kr.png", name: "South Korea"},
    {flag: "kw.png", name: "Kuwait"},
    {flag: "ky.png", name: "Cayman Islands"},
    {flag: "kz.png", name: "Kazakhstan"},
    {flag: "la.png", name: "Laos"},
    {flag: "lb.png", name: "Lebanon"},
    {flag: "lc.png", name: "Saint Lucia"},
    {flag: "li.png", name: "Liechtenstein"},
    {flag: "lk.png", name: "Sri Lanka"},
    {flag: "lr.png", name: "Liberia"},
    {flag: "ls.png", name: "Lesotho"},
    {flag: "lt.png", name: "Lithuania"},
    {flag: "lu.png", name: "Luxembourg"},
    {flag: "lv.png", name: "Latvia"},
    {flag: "ly.png", name: "Libya"},
    {flag: "ma.png", name: "Morocco"},
    {flag: "mc.png", name: "Monaco"},
    {flag: "md.png", name: "Moldova"},
    {flag: "me.png", name: "Montenegro"},
    {flag: "mf.png", name: "Saint Martin"},
    {flag: "mg.png", name: "Madagascar"},
    {flag: "mh.png", name: "Marshall Islands"},
    {flag: "mk.png", name: "North Macedonia"},
    {flag: "ml.png", name: "Mali"},
    {flag: "mm.png", name: "Myanmar"},
    {flag: "mn.png", name: "Mongolia"},
    {flag: "mo.png", name: "Macau"},
    {flag: "mp.png", name: "Northern Mariana Islands"},
    {flag: "mq.png", name: "Martinique"},
    {flag: "mr.png", name: "Mauritania"},
    {flag: "ms.png", name: "Montserrat"},
    {flag: "mt.png", name: "Malta"},
    {flag: "mu.png", name: "Mauritius"},
    {flag: "mv.png", name: "Maldives"},
    {flag: "mw.png", name: "Malawi"},
    {flag: "mx.png", name: "Mexico"},
    {flag: "my.png", name: "Malaysia"},
    {flag: "mz.png", name: "Mozambique"},
    {flag: "na.png", name: "Namibia"},
    {flag: "nc.png", name: "New Caledonia"},
    {flag: "ne.png", name: "Niger"},
    {flag: "nf.png", name: "Norfolk Island"},
    {flag: "ng.png", name: "Nigeria"},
    {flag: "ni.png", name: "Nicaragua"},
    {flag: "nl.png", name: "Netherlands"},
    {flag: "no.png", name: "Norway"},
    {flag: "np.png", name: "Nepal"},
    {flag: "nr.png", name: "Nauru"},
    {flag: "nu.png", name: "Niue"},
    {flag: "nz.png", name: "New Zealand"},
    {flag: "om.png", name: "Oman"},
    {flag: "pa.png", name: "Panama"},
    {flag: "pe.png", name: "Peru"},
    {flag: "pf.png", name: "French Polynesia"},
    {flag: "pg.png", name: "Papua New Guinea"},
    {flag: "ph.png", name: "Philippines"},
    {flag: "pk.png", name: "Pakistan"},
    {flag: "pl.png", name: "Poland"},
    {flag: "pm.png", name: "Saint Pierre and Miquelon"},
    {flag: "pn.png", name: "Pitcairn Islands"},
    {flag: "pr.png", name: "Puerto Rico"},
    {flag: "ps.png", name: "Palestine"},
    {flag: "pt.png", name: "Portugal"},
    {flag: "pw.png", name: "Palau"},
    {flag: "py.png", name: "Paraguay"},
    {flag: "qa.png", name: "Qatar"},
    {flag: "re.png", name: "Réunion"},
    {flag: "ro.png", name: "Romania"},
    {flag: "rs.png", name: "Serbia"},
    {flag: "ru.png", name: "Russia"},
    {flag: "rw.png", name: "Rwanda"},
    {flag: "sa.png", name: "Saudi Arabia"},
    {flag: "sb.png", name: "Solomon Islands"},
    {flag: "sc.png", name: "Seychelles"},
    {flag: "sd.png", name: "Sudan"},
    {flag: "se.png", name: "Sweden"},
    {flag: "sg.png", name: "Singapore"},
    {flag: "sh.png", name: "Saint Helena, Ascension and Tristan da Cunha"},
    {flag: "si.png", name: "Slovenia"},
    {flag: "sj.png", name: "Svalbard and Jan Mayen"},
    {flag: "sk.png", name: "Slovakia"},
    {flag: "sl.png", name: "Sierra Leone"},
    {flag: "sm.png", name: "San Marino"},
    {flag: "sn.png", name: "Senegal"},
    {flag: "so.png", name: "Somalia"},
    {flag: "sr.png", name: "Suriname"},
    {flag: "ss.png", name: "South Sudan"},
    {flag: "st.png", name: "São Tomé and Príncipe"},
    {flag: "sv.png", name: "El Salvador"},
    {flag: "sx.png", name: "Sint Maarten"},
    {flag: "sy.png", name: "Syria"},
    {flag: "sz.png", name: "Eswatini (Swaziland)"},
    {flag: "tc.png", name: "Turks and Caicos Islands"},
    {flag: "td.png", name: "Chad"},
    {flag: "tf.png", name: "French Southern and Antarctic Lands"},
    {flag: "tg.png", name: "Togo"},
    {flag: "th.png", name: "Thailand"},
    {flag: "tj.png", name: "Tajikistan"},
    {flag: "tk.png", name: "Tokelau"},
    {flag: "tl.png", name: "Timor-Leste"},
    {flag: "tm.png", name: "Turkmenistan"},
    {flag: "tn.png", name: "Tunisia"},
    {flag: "to.png", name: "Tonga"},
    {flag: "tr.png", name: "Turkey"},
    {flag: "tt.png", name: "Trinidad and Tobago"},
    {flag: "tv.png", name: "Tuvalu"},
    {flag: "tw.png", name: "Taiwan"},
    {flag: "tz.png", name: "Tanzania"},
    {flag: "ua.png", name: "Ukraine"},
    {flag: "ug.png", name: "Uganda"},
    {flag: "um.png", name: "United States Minor Outlying Islands"},
    {flag: "us.png", name: "United States"},
    {flag: "uy.png", name: "Uruguay"},
    {flag: "uz.png", name: "Uzbekistan"},
    {flag: "va.png", name: "Vatican City (Holy See)"},
    {flag: "vc.png", name: "Saint Vincent and the Grenadines"},
    {flag: "ve.png", name: "Venezuela"},
    {flag: "vg.png", name: "British Virgin Islands"},
    {flag: "vi.png", name: "United States Virgin Islands"},
    {flag: "vn.png", name: "Vietnam"},
    {flag: "vu.png", name: "Vanuatu"},
    {flag: "wf.png", name: "Wallis and Futuna"},
    {flag: "ws.png", name: "Samoa"},
    {flag: "xk.png", name: "Kosovo"},
    {flag: "ye.png", name: "Yemen"},
    {flag: "yt.png", name: "Mayotte"},
    {flag: "za.png", name: "South Africa"},
    {flag: "zm.png", name: "Zambia"},
    {flag: "zw.png", name: "Zimbabwe"
}];
